### ISSUE TITLE
Twitch extension boxes that tie to marathons

### ISSUE THREAD

**Issue by Planks** [esamarathon/oengus-webapp#35]
This job specifies a pair of [twitch extension](https://dev.twitch.tv/extensions) boxes that can be added to a twitch channel channel in order to add rich marathon data below the stream, and in a tab on mobile platforms.

The two boxes that are required are: **Now and Next** and **Follow the runner(s)**

Magic should happen behind the scenes to select the right data set. A marathon on oengus has a twitch channel set. Thus, if a box is added to a twitch channel, the extension can learn which twitch channel is being viewed.

The boxes should always display the **next schedule that is due to apply on the channel**. It is worth remembering that more than one marathon can have the same channel set. If a channel has no marathon due, a friendly advert for oengus should be displayed :)

### Now and next

The now and next widget will show the current and next run in the marathon, per the schedule published on oengus.io. If twitch is able to pass on the game name to the application, MAAAAAYBE a bit of magic could be applied so that the "current game" does not step early if the marathon is behind.

It should have two views: overview and detail, in the same design language as v2, plus a branded link to the marathon's schedule page.

![image](https://user-images.githubusercontent.com/16325321/133935395-5f12cca7-f03c-440a-8f78-47a4dd599dbc.png)

### Follow the runner(s)

The follow the runners widget should follow the same logic as the now and next widget, showing the runners of the current run in more detail.

It should have two views: overview and detail, that mimic the design language of the profile pages on the website. It should also include a branded link to the marathon's schedule page (overview) or the runner's profile page (detail)

The overview should display up to 6 runners mini cards. The mini card should display their gravatar, handle, pronouns and country (if set). It should include an instant follow button like esa's featured runners channels.

The detail page should add in any further socials that the user has set, such as srcom, twitch and twitter, scaling text and icons to fit without the need for a scroll bar.

![image](https://user-images.githubusercontent.com/16325321/133935457-b8f96e27-a69f-430b-801a-3dc2a59ca532.png)

**Comment by duncte123** [comment]
Documentation: https://dev.twitch.tv/docs/extensions

**Comment by duncte123** [comment]
Extra pages to be created:
- configuration page
- error page for when marathon id is not set/invalid (store invalid marathon id state in config)

**Comment by duncte123** [comment]
Note: use the javascript template API instead of a framework, will load way faster with less overhead
