### ISSUE TITLE
Clickable runner names (without expanding)

### ISSUE THREAD

**Issue by Wolsk** [esamarathon/oengus-webapp#81]
Adding markdown to make runner names clickable on a schedule without expanding would be great (or not adding markdown and just making it link to their profile page like normal). I understand if this cannot be done because of how the site pulls account info for a schedule; I just wanted to reduce the number of clicks needed to find someone's preferred platform for streaming and/or making content.

![image](https://github.com/esamarathon/oengus-webapp/assets/14972008/dd093e60-720e-4e8d-b30f-9b8d2af98517)

**Comment by duncte123** [comment]
Closing this as this is implemented now https://oengus.io/marathon/sss24/schedule/schedule-1
